project:
  type: website
  output-dir: docs

website:
  title: "DRP-HCB-Bioinformatics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: training.qmd
        text: "Training Events"
      - href: training_resources.qmd
        text: "Training Resources"
      - href: best_practices.qmd
        text: "Best Practices"
      - href: bioinformatics_live.qmd
        text: "Bioinformatics Live"
      #- href: resources.qmd
      #  text: "Resources"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-newwindow: true

editor: visual

